version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
  pre_build:
    commands:
      - export BUILD_ID=`date -u +%s`
      - echo "Build ID (UTC timestamp in seconds) $BUILD_ID"
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --registry-ids 118533919239)
  build:
    commands:
      - ./gradlew check pushDockerImage
